### ISSUE TITLE
Refactor/Address tech debt in Negotiation Card and Report Pages

### ISSUE THREAD

**Issue by sei-aderr** [mlte-team/mlte#359]
- [x] Simplify data model of report to directly load the backend object.
- [x] Load options for Problem Type and Classification drop downs from the schemas
- [x] Move `fetchArtifact` from report.vue into a composable
- [x] - Figure out the useFetch status bug, or just remove that check. Was an issue with nuxt versioning.
- [x] Adjust report findings to be stored outside of the form and have `loadFindings` populate that field correctly. 
- [x] Adjust useFetch within `fetchArtifact` to just use fetch
- [x] Improve how the version of the package is displayed in the frontend
- [x] Define types for findings in the report page, and any other missing types in the frontend
- [x] Adjust all calls in methods to not use useFetch, and instead properly use $fetch. Plan to be done by use of `fetchArtifact` method

**Comment by sei-aderr** [comment]
@krmaffey @sebastian-echeverria 

Looking into package version display on the frontend. Currently I just had it as a hard coded value in the base layout, which has now become outdated. 

I see that it looks like the version is stored in `.bumpversion.cfg` and `pyproject.toml`. Not 100% what the best way to handle this would be. My simple but annoying solution would just be we adjust the version on the frontend layout manually whenever we update the version in those other files. Wondering if you guys had any other ideas

**Comment by sei-aderr** [comment]
Loading the options from the schema is going to be backlogged/addressed in #362. If we go ahead with that idea then the schema loading is invalidated so not going to spend time implementing it now.

**Comment by sei-aderr** [comment]
Some typing adding, some will be removed in namespace update so waiting for after that change to look into it again

**Comment by sebastian-echeverria** [comment]
@sei-aderr 
> 
> Looking into package version display on the frontend. Currently I just had it as a hard coded value in the base layout, which has now become outdated.
> 
> I see that it looks like the version is stored in `.bumpversion.cfg` and `pyproject.toml`. Not 100% what the best way to handle this would be. My simple but annoying solution would just be we adjust the version on the frontend layout manually whenever we update the version in those other files. Wondering if you guys had any other ideas

We seem to be using a package called bump2version, which uses tha cfg file, to update versions as needed. If you look at the config file, you can see that when that tool is used, it updates the version not only in the .toml file, but also in one of the docs file. Apparently, it can update versions in different files as requested, as described in the docs/docs/development.md file. In fact, the version in the .toml file is not updated manually, but automatically when calling bump2version.

I would recommend creating a file, or isolating the version in a file in the frontend (it can be any type of file really), where you put the current version manually, and add that file to the list in the cfg file . Every time we bump the version using bump2version, that version in your frontend file will be updated as well. (Since the current version is a parameter in the .cfg file, I assume the tool just looks for that string and replaces it with the next version, depending on the type of version passed in the command line. I recommend putting the version in a small file to avoid the issue of accidentally having another string at some point which coincidentally has the same number as the version but means something else, and getting it changed as well.)

**Comment by sei-aderr** [comment]
@sebastian-echeverria 

Thanks for the info. I got it working using bump version to manage the version for the frontend. Will open a PR once we merge the namespace changes and I can rebase on that.

**Comment by sebastian-echeverria** [comment]
Addressed by #367
