### ISSUE TITLE
Create a default sample artifact store

### ISSUE THREAD

**Issue by sebastian-echeverria** [mlte-team/mlte#462]
The Jupyter Notebook demos currently allow the creation of a sample artifact store, but they have no instructions on how to access it through the MLTE UI, and they may not be too easy to run. Find a way to have a sample artifact store and instructions to easily use it.

NOTE: it may be possible to improve the compatibility of the notebooks and have the instructions just be a script to run all those notebooks and generate the results. Note however, that this could be really slow, so having an updated version of this already store in the repo could make it easier for people to see how things look like when using the UI.

**Comment by sebastian-echeverria** [comment]
Start at least with the negotiation card, in a subfolder in the /demo folder.

Update docs for getting started to point to this negotiation card.

**Comment by GALewis** [comment]
Attached is a negotiation card for the flower identification model. Because it is simply an example, I want to make sure that it fits well with the model and the test code.

@rbedman Can you take the first pass and review everything, especially Development Compute Resources and the Input and Output Specifications. I also need help with the Data Section. The easiest, I think, would be to do this in the UI? The name of the model is flower-classifier and the version is 1.0

@sebastian-echeverria After Rob is done, your review would also be useful.

Thanks![flower-classifier-1-0.json](https://github.com/user-attachments/files/17155843/flower-classifier-1-0.json)

**Comment by rbedman** [comment]
Grace,

I can't figure out how to view that in the ui - but I looked at the raw
javascript and think we are broadly in agreement for quality attribute
scenarios - slightly different wordings (mine are wordier - and somehow I
have two more).

Here is my version of the same that I made in the notebook. I've also got
the data in this version - something we should talk about on Tuesday is
that, given the number of labels, the data and label descriptions will be
harder to enter through the UI. We can discuss that on Tuesday

--Rob

**Comment by GALewis** [comment]
Attached is a new version of the Negotiation Card. There are a couple of things to do:

@rbedman Please take a look again and make sure that data, input specification, and output specification are correct. Notice the values that I have marked as outputs that indicate problems to make sure that your code matches those values.

@sebastian-echeverria Can you do a sanity check, especially for resource numbers?

[flower-classifier-1-0.json](https://github.com/user-attachments/files/17192951/flower-classifier-1-0.json)

**Comment by sebastian-echeverria** [comment]
In the wiki we have 3000 b as the storage for the prod resources, which is what we are using in the demo, so I would change that from the 128 GB it currently has.

**Comment by GALewis** [comment]
Assuming 3000B = 3MB, the new version is attached.

[flower-classifier-1-0.json](https://github.com/user-attachments/files/17194784/flower-classifier-1-0.json)

**Comment by sebastian-echeverria** [comment]
Fixed in #489
