### ISSUE TITLE
Decide on INCOSE presentation, tutorial, or nothing

### ISSUE THREAD

**Issue by rbedman** [mlte-team/mlte#501]

**Comment by rbedman** [comment]
Past tutorials: Half day or Full day

**Comment by krmaffey** [comment]
Submissions for [presentations](https://www.incose.org/docs/default-source/events-documents/is2025/promotion/iscall-for-submissions.pdf?sfvrsn=e9a257c7_2) includes an extended abstract of no more than 1,000 words and include:
- An overview of the topic – define the systems engineering (SE) challenge of interest and its context
- Clearly identify specific related industries – explain why the problem is important and is worth studying under a SE approach
- Provide what the audience will take away from the presentation – outline methods and describe expected results
- Provide background

**Comment by rbedman** [comment]
Decided on a presentation - 1000 word abstract. We don't have enough content for a tutorial, don't want to commit to a full paper. 

@krmaffey will outline, we will review on 11/11

**Comment by krmaffey** [comment]
@rbedman and @krmaffey are writing the abstract, we decided to submit for a presentation. Closing this issue, the submission is addressed by issue #537
